name: nfc_manager_example
description: Demonstrates how to use the nfc_manager plugin.
publish_to: none

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nfc_manager:
    path: ../

flutter:
  uses-material-design: true
