name: nfc_manager
description: A Flutter plugin for accessing the NFC features on Android and iOS.
version: 4.0.0-dev
homepage: https://github.com/okadan/flutter-nfc-manager

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ndef_record:

dev_dependencies:
  pigeon:

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.plugins.nfcmanager
        pluginClass: NfcManagerPlugin
      ios:
        pluginClass: NfcManagerPlugin
